### PR TITLE
use sort -V to compare version, should fix issue #26

### LINKED ISSUE #26: Klipper version comparaison is wrong
Here is an example :
```
[...]
current version 0.0.6-5-g932ac81
[...]
-- Update Mcus --
spider [mcu] version is v0.13.0-71-g3cf8899a5  => v0.13.0-114-g841a9ca2f.
You gonna flash an older firmware !
Update firmware of spider [mcu] ? [yN]: 
ebb36 [mcu toolhead] version is v0.13.0-71-g3cf8899a5  => v0.13.0-114-g841a9ca2f.
You gonna flash an older firmware !
```

I think we should use something based on sort -V (to handle versions):
```
printf "v0.13.0-71-g3cf8899a5\nv0.13.0-114-g841a9ca2f\n" | sort -V
v0.13.0-71-g3cf8899a5
v0.13.0-114-g841a9ca2f
```
so some function like that:
```
verlte() {
    printf '%s\n' "$1" "$2" | sort -C -V
}

verlt() {
    ! verlte "$2" "$1"
}
```

### PR DESCRIPTION
**Pull request by beavis69**

### CODE REVIEW

File: scripts/mcus.sh [hunk 1]
```diff
@@ -144,7 +144,7 @@ function update_mcus() {
       elif [ -n $version ]; then
         echo -e "$mcu_str version is ${GREEN}${version}" \
           "${DEFAULT} => ${GREEN}$k_local_version${DEFAULT}."
-        [ "$version" \> $k_local_version ] && def=n \
+        [ $(printf '%s\n' "$version" "$k_local_version" | sort -V | tail -n1) == "$version" ] && def=n \
```
Comment (fbeauKmi) [inline scripts/mcus.sh:147]: Why not
``printf "%s\n%s" "$k_local_version" "$version" | sort -C -V && def=n \`` 
?

**Review by fbeauKmi — COMMENTED** [review]
It works, just look at the question below.

**Comment by beavis69** [comment]
just because i tried it but i forgot  to remove the test [ ] so it was not working (lol)

it's working:

```
#!/bin/bash
version="v0.13.0-71-g3cf8899a5"
k_local_version="v0.13.0-114-g841a9ca2f"
printf '%s\n' "$k_local_version" "$version" | sort -V -C && echo "$version is more recent than $k_local_version"
printf '%s\n' "$version" "$k_local_version" | sort -V -C && echo "$k_local_version is more recent than $version"

it works :
v0.13.0-114-g841a9ca2f is more recent than v0.13.0-71-g3cf8899a5
```
